services:
  - type: web
    name: californiaearrings
    runtime: python
    plan: free
    buildCommand: curl -Ls https://astral.sh/uv/install.sh | sh && ~/.local/bin/uv sync --frozen
    startCommand: .venv/bin/gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
