from __future__ import annotations

from typing import Final

PhoneCountryOption = tuple[str, str, str]

DEFAULT_PHONE_COUNTRY_KEY: Final[str] = "us"
_PREFERRED_PHONE_COUNTRY_KEYS: Final[tuple[str, ...]] = ("us", "mx")

_PHONE_COUNTRY_OPTIONS_RAW: Final[tuple[PhoneCountryOption, ...]] = (
    ("us", "United States", "+1"),
    ("mx", "Mexico", "+52"),
    ("af", "Afghanistan", "+93"),
    ("al", "Albania", "+355"),
    ("dz", "Algeria", "+213"),
    ("ad", "Andorra", "+376"),
    ("ao", "Angola", "+244"),
    ("ag", "Antigua and Barbuda", "+1268"),
    ("ar", "Argentina", "+54"),
    ("am", "Armenia", "+374"),
    ("au", "Australia", "+61"),
    ("at", "Austria", "+43"),
    ("az", "Azerbaijan", "+994"),
    ("bs", "Bahamas", "+1242"),
    ("bh", "Bahrain", "+973"),
    ("bd", "Bangladesh", "+880"),
    ("bb", "Barbados", "+1246"),
    ("by", "Belarus", "+375"),
    ("be", "Belgium", "+32"),
    ("bz", "Belize", "+501"),
    ("bj", "Benin", "+229"),
    ("bt", "Bhutan", "+975"),
    ("bo", "Bolivia", "+591"),
    ("ba", "Bosnia and Herzegovina", "+387"),
    ("bw", "Botswana", "+267"),
    ("br", "Brazil", "+55"),
    ("bn", "Brunei", "+673"),
    ("bg", "Bulgaria", "+359"),
    ("bf", "Burkina Faso", "+226"),
    ("bi", "Burundi", "+257"),
    ("kh", "Cambodia", "+855"),
    ("cm", "Cameroon", "+237"),
    ("ca", "Canada", "+1"),
    ("cv", "Cape Verde", "+238"),
    ("cf", "Central African Republic", "+236"),
    ("td", "Chad", "+235"),
    ("cl", "Chile", "+56"),
    ("cn", "China", "+86"),
    ("co", "Colombia", "+57"),
    ("km", "Comoros", "+269"),
    ("cg", "Congo", "+242"),
    ("cr", "Costa Rica", "+506"),
    ("ci", "Cote d'Ivoire", "+225"),
    ("hr", "Croatia", "+385"),
    ("cu", "Cuba", "+53"),
    ("cy", "Cyprus", "+357"),
    ("cz", "Czech Republic", "+420"),
    ("cd", "Democratic Republic of the Congo", "+243"),
    ("dk", "Denmark", "+45"),
    ("dj", "Djibouti", "+253"),
    ("dm", "Dominica", "+1767"),
    ("do", "Dominican Republic", "+1809"),
    ("ec", "Ecuador", "+593"),
    ("eg", "Egypt", "+20"),
    ("sv", "El Salvador", "+503"),
    ("gq", "Equatorial Guinea", "+240"),
    ("er", "Eritrea", "+291"),
    ("ee", "Estonia", "+372"),
    ("sz", "Eswatini", "+268"),
    ("et", "Ethiopia", "+251"),
    ("fj", "Fiji", "+679"),
    ("fi", "Finland", "+358"),
    ("fr", "France", "+33"),
    ("ga", "Gabon", "+241"),
    ("gm", "Gambia", "+220"),
    ("ge", "Georgia", "+995"),
    ("de", "Germany", "+49"),
    ("gh", "Ghana", "+233"),
    ("gr", "Greece", "+30"),
    ("gd", "Grenada", "+1473"),
    ("gt", "Guatemala", "+502"),
    ("gn", "Guinea", "+224"),
    ("gw", "Guinea-Bissau", "+245"),
    ("gy", "Guyana", "+592"),
    ("ht", "Haiti", "+509"),
    ("hn", "Honduras", "+504"),
    ("hk", "Hong Kong", "+852"),
    ("hu", "Hungary", "+36"),
    ("is", "Iceland", "+354"),
    ("in", "India", "+91"),
    ("id", "Indonesia", "+62"),
    ("ir", "Iran", "+98"),
    ("iq", "Iraq", "+964"),
    ("ie", "Ireland", "+353"),
    ("il", "Israel", "+972"),
    ("it", "Italy", "+39"),
    ("jm", "Jamaica", "+1876"),
    ("jp", "Japan", "+81"),
    ("jo", "Jordan", "+962"),
    ("kz", "Kazakhstan", "+7"),
    ("ke", "Kenya", "+254"),
    ("ki", "Kiribati", "+686"),
    ("xk", "Kosovo", "+383"),
    ("kw", "Kuwait", "+965"),
    ("kg", "Kyrgyzstan", "+996"),
    ("la", "Laos", "+856"),
    ("lv", "Latvia", "+371"),
    ("lb", "Lebanon", "+961"),
    ("ls", "Lesotho", "+266"),
    ("lr", "Liberia", "+231"),
    ("ly", "Libya", "+218"),
    ("li", "Liechtenstein", "+423"),
    ("lt", "Lithuania", "+370"),
    ("lu", "Luxembourg", "+352"),
    ("mo", "Macau", "+853"),
    ("mg", "Madagascar", "+261"),
    ("mw", "Malawi", "+265"),
    ("my", "Malaysia", "+60"),
    ("mv", "Maldives", "+960"),
    ("ml", "Mali", "+223"),
    ("mt", "Malta", "+356"),
    ("mh", "Marshall Islands", "+692"),
    ("mr", "Mauritania", "+222"),
    ("mu", "Mauritius", "+230"),
    ("fm", "Micronesia", "+691"),
    ("md", "Moldova", "+373"),
    ("mc", "Monaco", "+377"),
    ("mn", "Mongolia", "+976"),
    ("me", "Montenegro", "+382"),
    ("ma", "Morocco", "+212"),
    ("mz", "Mozambique", "+258"),
    ("mm", "Myanmar", "+95"),
    ("na", "Namibia", "+264"),
    ("nr", "Nauru", "+674"),
    ("np", "Nepal", "+977"),
    ("nl", "Netherlands", "+31"),
    ("nz", "New Zealand", "+64"),
    ("ni", "Nicaragua", "+505"),
    ("ne", "Niger", "+227"),
    ("ng", "Nigeria", "+234"),
    ("kp", "North Korea", "+850"),
    ("mk", "North Macedonia", "+389"),
    ("no", "Norway", "+47"),
    ("om", "Oman", "+968"),
    ("pk", "Pakistan", "+92"),
    ("pw", "Palau", "+680"),
    ("ps", "Palestine", "+970"),
    ("pa", "Panama", "+507"),
    ("pg", "Papua New Guinea", "+675"),
    ("py", "Paraguay", "+595"),
    ("pe", "Peru", "+51"),
    ("ph", "Philippines", "+63"),
    ("pl", "Poland", "+48"),
    ("pt", "Portugal", "+351"),
    ("qa", "Qatar", "+974"),
    ("ro", "Romania", "+40"),
    ("ru", "Russia", "+7"),
    ("rw", "Rwanda", "+250"),
    ("kn", "Saint Kitts and Nevis", "+1869"),
    ("lc", "Saint Lucia", "+1758"),
    ("vc", "Saint Vincent and the Grenadines", "+1784"),
    ("ws", "Samoa", "+685"),
    ("sm", "San Marino", "+378"),
    ("st", "Sao Tome and Principe", "+239"),
    ("sa", "Saudi Arabia", "+966"),
    ("sn", "Senegal", "+221"),
    ("rs", "Serbia", "+381"),
    ("sc", "Seychelles", "+248"),
    ("sl", "Sierra Leone", "+232"),
    ("sg", "Singapore", "+65"),
    ("sk", "Slovakia", "+421"),
    ("si", "Slovenia", "+386"),
    ("sb", "Solomon Islands", "+677"),
    ("so", "Somalia", "+252"),
    ("za", "South Africa", "+27"),
    ("kr", "South Korea", "+82"),
    ("ss", "South Sudan", "+211"),
    ("es", "Spain", "+34"),
    ("lk", "Sri Lanka", "+94"),
    ("sd", "Sudan", "+249"),
    ("sr", "Suriname", "+597"),
    ("se", "Sweden", "+46"),
    ("ch", "Switzerland", "+41"),
    ("sy", "Syria", "+963"),
    ("tw", "Taiwan", "+886"),
    ("tj", "Tajikistan", "+992"),
    ("tz", "Tanzania", "+255"),
    ("th", "Thailand", "+66"),
    ("tl", "Timor-Leste", "+670"),
    ("tg", "Togo", "+228"),
    ("to", "Tonga", "+676"),
    ("tt", "Trinidad and Tobago", "+1868"),
    ("tn", "Tunisia", "+216"),
    ("tr", "Turkey", "+90"),
    ("tm", "Turkmenistan", "+993"),
    ("tv", "Tuvalu", "+688"),
    ("ug", "Uganda", "+256"),
    ("ua", "Ukraine", "+380"),
    ("ae", "United Arab Emirates", "+971"),
    ("gb", "United Kingdom", "+44"),
    ("uy", "Uruguay", "+598"),
    ("uz", "Uzbekistan", "+998"),
    ("vu", "Vanuatu", "+678"),
    ("va", "Vatican City", "+39"),
    ("ve", "Venezuela", "+58"),
    ("vn", "Vietnam", "+84"),
    ("ye", "Yemen", "+967"),
    ("zm", "Zambia", "+260"),
    ("zw", "Zimbabwe", "+263"),
)

_PHONE_COUNTRY_OPTIONS_BY_KEY: Final[dict[str, PhoneCountryOption]] = {
    key: (key, label, dial_code)
    for key, label, dial_code in _PHONE_COUNTRY_OPTIONS_RAW
}


def get_phone_country_option(country_key: str | None) -> PhoneCountryOption:
    normalized_key = (country_key or "").strip().lower()
    return _PHONE_COUNTRY_OPTIONS_BY_KEY.get(
        normalized_key,
        _PHONE_COUNTRY_OPTIONS_BY_KEY[DEFAULT_PHONE_COUNTRY_KEY],
    )


def build_checkout_phone_country_options() -> tuple[PhoneCountryOption, ...]:
    preferred = [
        _PHONE_COUNTRY_OPTIONS_BY_KEY[key]
        for key in _PREFERRED_PHONE_COUNTRY_KEYS
    ]
    preferred_keys = set(_PREFERRED_PHONE_COUNTRY_KEYS)
    remaining = sorted(
        (option for option in _PHONE_COUNTRY_OPTIONS_RAW if option[0] not in preferred_keys),
        key=lambda option: option[1],
    )
    return tuple([*preferred, *remaining])


CHECKOUT_PHONE_COUNTRY_OPTIONS: Final[tuple[PhoneCountryOption, ...]] = build_checkout_phone_country_options()
CHECKOUT_PHONE_COUNTRY_DISPLAY_BY_KEY: Final[dict[str, str]] = {
    key: f"{label} ({dial_code})"
    for key, label, dial_code in CHECKOUT_PHONE_COUNTRY_OPTIONS
}
CHECKOUT_PHONE_COUNTRY_KEY_BY_DISPLAY: Final[dict[str, str]] = {
    display.casefold(): key
    for key, display in CHECKOUT_PHONE_COUNTRY_DISPLAY_BY_KEY.items()
}


def get_phone_country_key_from_display(display_value: str | None) -> str:
    return CHECKOUT_PHONE_COUNTRY_KEY_BY_DISPLAY.get((display_value or "").strip().casefold(), "")